services:
  stackupPostgres:
    image: postgres
    container_name: stackupPostgres

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  identity-api:
    image: identity-api:latest
    container_name: identity-api
    build:
      context: .
      dockerfile: Servicios/Identity/IdentityAPI/PublicAPI/Dockerfile
    depends_on:
      - stackupPostgres
